
# Site settings
title: Monty Khanna
email: montykhanna007@hotmail.com
description: "Consultant - Software Engineer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: #username
github_username:  mackraja

# Build settings
markdown: kramdown

#
####################################
# Site Owner configuration
####################################
#
owner:
  name: Monty Khanna
  avatar: avatar.jpg
  job: "<a href=\"https://www.technossus.com/\" target=\"_blank\">@technossus</a>"
  bio: "8+ years of experience in software development integration of web based application.

Excellent knowledge and experience of Nodejs, Reactjs (Classes, Hooks), Typescript, Redux, Redux-Form, Hapijs, Swagger, Sequelizejs, ReactStrap, semantic-ui, Material-ui, Ant Designs, AngularJs, Mysql/Postgresql/Mssql/MongoDb"
  email: montykhanna007@hotmail.com
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mackraja
  stackoverflow: 4156989/monty
  linkedin: monty-khanna-b8515a54
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: mkmontykhanna
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  pdfFormat: 2021062420533309-07-2020.pdf
  docFormat: 2021062420233114-05-2021.doc
